# Generated by Django 5.0.2 on 2024-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('marinero', 'Marinero'), ('cabo', 'Cabo'), ('tercer_maestre', 'Tercer Maestre'), ('segundo_maestre', 'Segundo Maestre'), ('primer_maestre', 'Primer Maestre/Guardiamarina'), ('teniente_corbeta', 'Teniente de Corbeta'), ('teniente_fragata', 'Teniente de Fragata'), ('teniente_navio', 'Teniente de Navío'), ('capitan_corbeta', 'Capitán de Corbeta'), ('capitan_fragata', 'Capitán de Fragata'), ('capitan_navio', 'Capitán de Navío'), ('contralmirante', 'Contralmirante'), ('vicealmirante', 'Vicealmirante'), ('almirante', 'Almirante')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('will_attend', models.BooleanField(default=False)),
            ],
        ),
    ]
